const CartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  ADD_ITEM_TO_FAVORITE: "ADD_ITEM_TO_FAVORITE",
  REMOVE_ITEM_FROM_FAVORITE: "REMOVE_ITEM_FROM_FAVORITE",
};
export default CartActionTypes;
