const COLLECTION_DATA = [
  {
    id: 1,
    product_id: 6,
    name: "Brown Brim",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25000,
    like: false,
  },
  {
    id: 1,
    product_id: 7,
    name: "Blue Beanie",
    imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    price: 18000,
    like: false,
  },
  {
    id: 1,
    product_id: 8,
    name: "Brown Cowboy",
    imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
    price: 35000,
    like: false,
  },
  {
    id: 1,
    product_id: 9,
    name: "Grey Brim",
    imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
    price: 25000,
    like: false,
  },
  {
    id: 1,
    product_id: 10,
    name: "Green Beanie",
    imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
    price: 18000,
    like: false,
  },
  {
    id: 1,
    product_id: 11,
    name: "Palm Tree Cap",
    imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
    price: 14000,
    like: false,
  },
  {
    id: 1,
    product_id: 12,
    name: "Red Beanie",
    imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
    price: 18000,
    like: false,
  },
  {
    id: 1,
    product_id: 13,
    name: "Wolf Cap",
    imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
    price: 14000,
    like: false,
  },
  {
    id: 1,
    product_id: 14,
    name: "Blue Snapback",
    imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
    price: 16000,
    like: false,
  },
  {
    id: 2,
    product_id: 15,
    name: "Black Jean Shearling",
    imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
    price: 125000,
    like: false,
  },
  {
    id: 2,
    product_id: 16,
    name: "Blue Jean Jacket",
    imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
    price: 90000,
    like: false,
  },
  {
    id: 2,
    product_id: 17,
    name: "Grey Jean Jacket",
    imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    price: 90000,
    like: false,
  },
  {
    id: 2,
    product_id: 18,
    name: "Brown Shearling",
    imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
    price: 165000,
    like: false,
  },
  {
    id: 2,
    product_id: 19,
    name: "Tan Trench",
    imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    price: 185000,
    like: false,
  },
  {
    id: 3,
    product_id: 20,
    name: "Adidas NMD",
    imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
    price: 220000,
    like: false,
  },
  {
    id: 3,
    product_id: 21,
    name: "Adidas Yeezy",
    imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
    price: 280000,
    like: false,
  },
  {
    id: 3,
    product_id: 22,
    name: "Black Converse",
    imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
    price: 110000,
    like: false,
  },
  {
    id: 3,
    product_id: 23,
    name: "Nike White AirForce",
    imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
    price: 160000,
    like: false,
  },
  {
    id: 3,
    product_id: 24,
    name: "Nike Red High Tops",
    imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
    price: 160000,
    like: false,
  },
  {
    id: 3,
    product_id: 25,
    name: "Nike Brown High Tops",
    imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
    price: 160000,
    like: false,
  },
  {
    id: 3,
    product_id: 26,
    name: "Air Jordan Limited",
    imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
    price: 190000,
    like: false,
  },
  {
    id: 3,
    product_id: 27,
    name: "Timberlands",
    imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
    price: 200000,
    like: false,
  },
  {
    id: 4,
    product_id: 28,
    name: "Blue Tanktop",
    imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
    price: 25000,
    like: false,
  },
  {
    id: 4,
    product_id: 29,
    name: "Floral Blouse",
    imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
    price: 20000,
    like: false,
  },
  {
    id: 4,
    product_id: 30,
    name: "Floral Dress",
    imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
    price: 80000,
    like: false,
  },
  {
    id: 4,
    product_id: 31,
    name: "Red Dots Dress",
    imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
    price: 80000,
    like: false,
  },
  {
    id: 4,
    product_id: 32,
    name: "Striped Sweater",
    imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    price: 45000,
    like: false,
  },
  {
    id: 4,
    product_id: 33,
    name: "Yellow Track Suit",
    imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
    price: 135000,
    like: false,
  },
  {
    id: 4,
    product_id: 34,
    name: "White Blouse",
    imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
    price: 20000,
    like: false,
  },
  {
    id: 5,
    product_id: 35,
    name: "Camo Down Vest",
    imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
    price: 325000,
    like: false,
  },
  {
    id: 5,
    product_id: 36,
    name: "Floral T-shirt",
    imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
    price: 20000,
    like: false,
  },
  {
    id: 5,
    product_id: 37,
    name: "Black & White Longsleeve",
    imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
    price: 25000,
    like: false,
  },
  {
    id: 5,
    product_id: 38,
    name: "Pink T-shirt",
    imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
    price: 25000,
    like: false,
  },
  {
    id: 5,
    product_id: 39,
    name: "Jean Long Sleeve",
    imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
    price: 40000,
    like: false,
  },
  {
    id: 5,
    product_id: 40,
    name: "Burgundy T-shirt",
    imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
    price: 25000,
    like: false,
  },
];
export default COLLECTION_DATA;
